// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeVronskuWtCoLtL1aYRbSG9HovZST5ik',
    appId: '1:334636454148:android:893e15d19e0c96ac9fc051',
    messagingSenderId: '334636454148',
    projectId: 'nerd-notification-bc9b8',
    storageBucket: 'nerd-notification-bc9b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPVJ3a64tqalSiFSmaMQIjOsDzKP6x1y0',
    appId: '1:334636454148:ios:fefd612a45f1dac99fc051',
    messagingSenderId: '334636454148',
    projectId: 'nerd-notification-bc9b8',
    storageBucket: 'nerd-notification-bc9b8.firebasestorage.app',
    iosBundleId: 'com.example.quizAppGrad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEsZbCdyufkyfBzz759iPOFgWpkxnl35k',
    appId: '1:334636454148:web:00376dfa9fc893749fc051',
    messagingSenderId: '334636454148',
    projectId: 'nerd-notification-bc9b8',
    authDomain: 'nerd-notification-bc9b8.firebaseapp.com',
    storageBucket: 'nerd-notification-bc9b8.firebasestorage.app',
    measurementId: 'G-2VQK0MVT5D',
  );
}
